# Generated by Django 5.2.4 on 2025-08-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
