# Generated by Django 5.2.4 on 2025-08-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
