# Generated by Django 5.2.4 on 2025-10-03 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_evidence', models.CharField(blank=True, max_length=120)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=512)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('PENDING', 'PENDING'), ('PASSED', 'PASSED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='snapdo.todo')),
            ],
        ),
    ]
