# Generated by Django 5.2.4 on 2025-10-03 13:57

from django.db import migrations

def forwards_func(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Todo = apps.get_model("snapdo", "Todo")
    db_alias = schema_editor.connection.alias
    
    # Create a default user if it doesn't exist
    user, created = User.objects.using(db_alias).get_or_create(username="defaultuser")

    Todo.objects.using(db_alias).bulk_create([
        Todo(owner=user, title="Recycle plastics", description="Separate and clean plastic containers for recycling.", target_evidence="Photo of sorted plastics"),
        Todo(owner=user, title="Organize desk", description="Tidy up the desk, arrange stationery, and wipe the surface.", target_evidence="Photo of the clean desk"),
        Todo(owner=user, title="Water plants", description="Water all indoor and outdoor plants.", target_evidence="Photo of watered plants"),
        Todo(owner=user, title="Read a chapter of a book", description="Read at least one chapter of any book.", target_evidence="Photo of the book cover and page number"),
        Todo(owner=user, title="Wash dishes", description="Wash and dry all the dishes in the sink.", target_evidence="Photo of the empty and clean sink"),
    ])

def reverse_func(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Todo = apps.get_model("snapdo", "Todo")
    db_alias = schema_editor.connection.alias
    user = User.objects.using(db_alias).get(username="defaultuser")
    Todo.objects.using(db_alias).filter(
        owner=user,
        title__in=[
            "Recycle plastics",
            "Organize desk",
            "Water plants",
            "Read a chapter of a book",
            "Wash dishes",
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('snapdo', '0001_initial'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
